-- Aubergine Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#F2EBF4", bg = "#9F4473", gui = "bold" }, b = { fg = "#33243B", bg = "#D7CFDA" }, c = { fg = "#6A6070", bg = "#E7DDEA" } },
  insert = { a = { fg = "#F2EBF4", bg = "#2C6829", gui = "bold" }, b = { fg = "#33243B", bg = "#D7CFDA" }, c = { fg = "#6A6070", bg = "#E7DDEA" } },
  visual = { a = { fg = "#F2EBF4", bg = "#4B2063", gui = "bold" }, b = { fg = "#33243B", bg = "#D7CFDA" }, c = { fg = "#6A6070", bg = "#E7DDEA" } },
  replace = { a = { fg = "#F2EBF4", bg = "#96161F", gui = "bold" }, b = { fg = "#33243B", bg = "#D7CFDA" }, c = { fg = "#6A6070", bg = "#E7DDEA" } },
  command = { a = { fg = "#F2EBF4", bg = "#826003", gui = "bold" }, b = { fg = "#33243B", bg = "#D7CFDA" }, c = { fg = "#6A6070", bg = "#E7DDEA" } },
  terminal = { a = { fg = "#F2EBF4", bg = "#006165", gui = "bold" }, b = { fg = "#33243B", bg = "#D7CFDA" }, c = { fg = "#6A6070", bg = "#E7DDEA" } },
  inactive = { a = { fg = "#7A6A84", bg = "#E7DDEA" }, b = { fg = "#7A6A84", bg = "#E7DDEA" }, c = { fg = "#7A6A84", bg = "#E7DDEA" } },
}
