-- Aubergine Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#3A2845", bg = "#F68AA1", gui = "bold" }, b = { fg = "#EFE5F2", bg = "#53425D" }, c = { fg = "#B0A3B5", bg = "#2E1F38" } },
  insert = { a = { fg = "#3A2845", bg = "#8AC975", gui = "bold" }, b = { fg = "#EFE5F2", bg = "#53425D" }, c = { fg = "#B0A3B5", bg = "#2E1F38" } },
  visual = { a = { fg = "#3A2845", bg = "#BC9EF9", gui = "bold" }, b = { fg = "#EFE5F2", bg = "#53425D" }, c = { fg = "#B0A3B5", bg = "#2E1F38" } },
  replace = { a = { fg = "#3A2845", bg = "#F56F6B", gui = "bold" }, b = { fg = "#EFE5F2", bg = "#53425D" }, c = { fg = "#B0A3B5", bg = "#2E1F38" } },
  command = { a = { fg = "#3A2845", bg = "#FDCC66", gui = "bold" }, b = { fg = "#EFE5F2", bg = "#53425D" }, c = { fg = "#B0A3B5", bg = "#2E1F38" } },
  terminal = { a = { fg = "#3A2845", bg = "#49D7CE", gui = "bold" }, b = { fg = "#EFE5F2", bg = "#53425D" }, c = { fg = "#B0A3B5", bg = "#2E1F38" } },
  inactive = { a = { fg = "#A290B0", bg = "#2E1F38" }, b = { fg = "#A290B0", bg = "#2E1F38" }, c = { fg = "#A290B0", bg = "#2E1F38" } },
}
