-- Clay for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#DDCEC8", bg = "#862D41", gui = "bold" }, b = { fg = "#463B3C", bg = "#C8B9B4" }, c = { fg = "#584F4E", bg = "#CFC1BB" } },
  insert = { a = { fg = "#DDCEC8", bg = "#165A17", gui = "bold" }, b = { fg = "#463B3C", bg = "#C8B9B4" }, c = { fg = "#584F4E", bg = "#CFC1BB" } },
  visual = { a = { fg = "#DDCEC8", bg = "#3C0E55", gui = "bold" }, b = { fg = "#463B3C", bg = "#C8B9B4" }, c = { fg = "#584F4E", bg = "#CFC1BB" } },
  replace = { a = { fg = "#DDCEC8", bg = "#8D001D", gui = "bold" }, b = { fg = "#463B3C", bg = "#C8B9B4" }, c = { fg = "#584F4E", bg = "#CFC1BB" } },
  command = { a = { fg = "#DDCEC8", bg = "#724E00", gui = "bold" }, b = { fg = "#463B3C", bg = "#C8B9B4" }, c = { fg = "#584F4E", bg = "#CFC1BB" } },
  terminal = { a = { fg = "#DDCEC8", bg = "#00554E", gui = "bold" }, b = { fg = "#463B3C", bg = "#C8B9B4" }, c = { fg = "#584F4E", bg = "#CFC1BB" } },
  inactive = { a = { fg = "#66585A", bg = "#CFC1BB" }, b = { fg = "#66585A", bg = "#CFC1BB" }, c = { fg = "#66585A", bg = "#CFC1BB" } },
}
