-- Forest Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#ECF0E6", bg = "#A8474B", gui = "bold" }, b = { fg = "#26362A", bg = "#D0D6CC" }, c = { fg = "#5E685E", bg = "#DFE6D8" } },
  insert = { a = { fg = "#ECF0E6", bg = "#2D6828", gui = "bold" }, b = { fg = "#26362A", bg = "#D0D6CC" }, c = { fg = "#5E685E", bg = "#DFE6D8" } },
  visual = { a = { fg = "#ECF0E6", bg = "#482165", gui = "bold" }, b = { fg = "#26362A", bg = "#D0D6CC" }, c = { fg = "#5E685E", bg = "#DFE6D8" } },
  replace = { a = { fg = "#ECF0E6", bg = "#951920", gui = "bold" }, b = { fg = "#26362A", bg = "#D0D6CC" }, c = { fg = "#5E685E", bg = "#DFE6D8" } },
  command = { a = { fg = "#ECF0E6", bg = "#846007", gui = "bold" }, b = { fg = "#26362A", bg = "#D0D6CC" }, c = { fg = "#5E685E", bg = "#DFE6D8" } },
  terminal = { a = { fg = "#ECF0E6", bg = "#006565", gui = "bold" }, b = { fg = "#26362A", bg = "#D0D6CC" }, c = { fg = "#5E685E", bg = "#DFE6D8" } },
  inactive = { a = { fg = "#647568", bg = "#DFE6D8" }, b = { fg = "#647568", bg = "#DFE6D8" }, c = { fg = "#647568", bg = "#DFE6D8" } },
}
