-- Forest Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#2A3A2E", bg = "#E58F8F", gui = "bold" }, b = { fg = "#E6EDE0", bg = "#445347" }, c = { fg = "#A4AEA2", bg = "#1F2C23" } },
  insert = { a = { fg = "#2A3A2E", bg = "#8CC775", gui = "bold" }, b = { fg = "#E6EDE0", bg = "#445347" }, c = { fg = "#A4AEA2", bg = "#1F2C23" } },
  visual = { a = { fg = "#2A3A2E", bg = "#CA9AF3", gui = "bold" }, b = { fg = "#E6EDE0", bg = "#445347" }, c = { fg = "#A4AEA2", bg = "#1F2C23" } },
  replace = { a = { fg = "#2A3A2E", bg = "#FC776B", gui = "bold" }, b = { fg = "#E6EDE0", bg = "#445347" }, c = { fg = "#A4AEA2", bg = "#1F2C23" } },
  command = { a = { fg = "#2A3A2E", bg = "#FFD46C", gui = "bold" }, b = { fg = "#E6EDE0", bg = "#445347" }, c = { fg = "#A4AEA2", bg = "#1F2C23" } },
  terminal = { a = { fg = "#2A3A2E", bg = "#4ED5C8", gui = "bold" }, b = { fg = "#E6EDE0", bg = "#445347" }, c = { fg = "#A4AEA2", bg = "#1F2C23" } },
  inactive = { a = { fg = "#8CA08C", bg = "#1F2C23" }, b = { fg = "#8CA08C", bg = "#1F2C23" }, c = { fg = "#8CA08C", bg = "#1F2C23" } },
}
