-- Indigo Dusk Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#EDECF5", bg = "#A54644", gui = "bold" }, b = { fg = "#2A2B4A", bg = "#D2D1DD" }, c = { fg = "#616276", bg = "#E0DEEE" } },
  insert = { a = { fg = "#EDECF5", bg = "#2C6929", gui = "bold" }, b = { fg = "#2A2B4A", bg = "#D2D1DD" }, c = { fg = "#616276", bg = "#E0DEEE" } },
  visual = { a = { fg = "#EDECF5", bg = "#3B256C", gui = "bold" }, b = { fg = "#2A2B4A", bg = "#D2D1DD" }, c = { fg = "#616276", bg = "#E0DEEE" } },
  replace = { a = { fg = "#EDECF5", bg = "#941A1F", gui = "bold" }, b = { fg = "#2A2B4A", bg = "#D2D1DD" }, c = { fg = "#616276", bg = "#E0DEEE" } },
  command = { a = { fg = "#EDECF5", bg = "#826000", gui = "bold" }, b = { fg = "#2A2B4A", bg = "#D2D1DD" }, c = { fg = "#616276", bg = "#E0DEEE" } },
  terminal = { a = { fg = "#EDECF5", bg = "#006266", gui = "bold" }, b = { fg = "#2A2B4A", bg = "#D2D1DD" }, c = { fg = "#616276", bg = "#E0DEEE" } },
  inactive = { a = { fg = "#6D6C8C", bg = "#E0DEEE" }, b = { fg = "#6D6C8C", bg = "#E0DEEE" }, c = { fg = "#6D6C8C", bg = "#E0DEEE" } },
}
