-- Indigo Dusk Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#2C2D4A", bg = "#FE9D9A", gui = "bold" }, b = { fg = "#E8E6F2", bg = "#464762" }, c = { fg = "#A6A5B7", bg = "#212239" } },
  insert = { a = { fg = "#2C2D4A", bg = "#8CC874", gui = "bold" }, b = { fg = "#E8E6F2", bg = "#464762" }, c = { fg = "#A6A5B7", bg = "#212239" } },
  visual = { a = { fg = "#2C2D4A", bg = "#CC9BF3", gui = "bold" }, b = { fg = "#E8E6F2", bg = "#464762" }, c = { fg = "#A6A5B7", bg = "#212239" } },
  replace = { a = { fg = "#2C2D4A", bg = "#F66E6B", gui = "bold" }, b = { fg = "#E8E6F2", bg = "#464762" }, c = { fg = "#A6A5B7", bg = "#212239" } },
  command = { a = { fg = "#2C2D4A", bg = "#FDCD67", gui = "bold" }, b = { fg = "#E8E6F2", bg = "#464762" }, c = { fg = "#A6A5B7", bg = "#212239" } },
  terminal = { a = { fg = "#2C2D4A", bg = "#47D5D0", gui = "bold" }, b = { fg = "#E8E6F2", bg = "#464762" }, c = { fg = "#A6A5B7", bg = "#212239" } },
  inactive = { a = { fg = "#9594B8", bg = "#212239" }, b = { fg = "#9594B8", bg = "#212239" }, c = { fg = "#9594B8", bg = "#212239" } },
}
