-- Lagoon Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#E8F0EE", bg = "#A3483F", gui = "bold" }, b = { fg = "#1F3A3F", bg = "#CCD7D6" }, c = { fg = "#57696B", bg = "#DCE7E4" } },
  insert = { a = { fg = "#E8F0EE", bg = "#2E6825", gui = "bold" }, b = { fg = "#1F3A3F", bg = "#CCD7D6" }, c = { fg = "#57696B", bg = "#DCE7E4" } },
  visual = { a = { fg = "#E8F0EE", bg = "#4C1F63", gui = "bold" }, b = { fg = "#1F3A3F", bg = "#CCD7D6" }, c = { fg = "#57696B", bg = "#DCE7E4" } },
  replace = { a = { fg = "#E8F0EE", bg = "#93181E", gui = "bold" }, b = { fg = "#1F3A3F", bg = "#CCD7D6" }, c = { fg = "#57696B", bg = "#DCE7E4" } },
  command = { a = { fg = "#E8F0EE", bg = "#82620C", gui = "bold" }, b = { fg = "#1F3A3F", bg = "#CCD7D6" }, c = { fg = "#57696B", bg = "#DCE7E4" } },
  terminal = { a = { fg = "#E8F0EE", bg = "#00685D", gui = "bold" }, b = { fg = "#1F3A3F", bg = "#CCD7D6" }, c = { fg = "#57696B", bg = "#DCE7E4" } },
  inactive = { a = { fg = "#5D7674", bg = "#DCE7E4" }, b = { fg = "#5D7674", bg = "#DCE7E4" }, c = { fg = "#5D7674", bg = "#DCE7E4" } },
}
