-- Lagoon Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#24393D", bg = "#EB8878", gui = "bold" }, b = { fg = "#E3EEEA", bg = "#3F5255" }, c = { fg = "#A0AFAD", bg = "#1A2B2F" } },
  insert = { a = { fg = "#24393D", bg = "#8DC773", gui = "bold" }, b = { fg = "#E3EEEA", bg = "#3F5255" }, c = { fg = "#A0AFAD", bg = "#1A2B2F" } },
  visual = { a = { fg = "#24393D", bg = "#C59CF7", gui = "bold" }, b = { fg = "#E3EEEA", bg = "#3F5255" }, c = { fg = "#A0AFAD", bg = "#1A2B2F" } },
  replace = { a = { fg = "#24393D", bg = "#FB766D", gui = "bold" }, b = { fg = "#E3EEEA", bg = "#3F5255" }, c = { fg = "#A0AFAD", bg = "#1A2B2F" } },
  command = { a = { fg = "#24393D", bg = "#FFD26B", gui = "bold" }, b = { fg = "#E3EEEA", bg = "#3F5255" }, c = { fg = "#A0AFAD", bg = "#1A2B2F" } },
  terminal = { a = { fg = "#24393D", bg = "#52D4C3", gui = "bold" }, b = { fg = "#E3EEEA", bg = "#3F5255" }, c = { fg = "#A0AFAD", bg = "#1A2B2F" } },
  inactive = { a = { fg = "#86A3A1", bg = "#1A2B2F" }, b = { fg = "#86A3A1", bg = "#1A2B2F" }, c = { fg = "#86A3A1", bg = "#1A2B2F" } },
}
