-- Mauve for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#D6C7D0", bg = "#7E2B4C", gui = "bold" }, b = { fg = "#413642", bg = "#C1B3BC" }, c = { fg = "#534B53", bg = "#C8BAC2" } },
  insert = { a = { fg = "#D6C7D0", bg = "#155813", gui = "bold" }, b = { fg = "#413642", bg = "#C1B3BC" }, c = { fg = "#534B53", bg = "#C8BAC2" } },
  visual = { a = { fg = "#D6C7D0", bg = "#370A55", gui = "bold" }, b = { fg = "#413642", bg = "#C1B3BC" }, c = { fg = "#534B53", bg = "#C8BAC2" } },
  replace = { a = { fg = "#D6C7D0", bg = "#8A0019", gui = "bold" }, b = { fg = "#413642", bg = "#C1B3BC" }, c = { fg = "#534B53", bg = "#C8BAC2" } },
  command = { a = { fg = "#D6C7D0", bg = "#684C00", gui = "bold" }, b = { fg = "#413642", bg = "#C1B3BC" }, c = { fg = "#534B53", bg = "#C8BAC2" } },
  terminal = { a = { fg = "#D6C7D0", bg = "#00564F", gui = "bold" }, b = { fg = "#413642", bg = "#C1B3BC" }, c = { fg = "#534B53", bg = "#C8BAC2" } },
  inactive = { a = { fg = "#625560", bg = "#C8BAC2" }, b = { fg = "#625560", bg = "#C8BAC2" }, c = { fg = "#625560", bg = "#C8BAC2" } },
}
