-- Ryoku Dark for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#16110B", bg = "#E63D32", gui = "bold" }, b = { fg = "#CDC4BA", bg = "#302A24" }, c = { fg = "#8D857D", bg = "#0F0B07" } },
  insert = { a = { fg = "#16110B", bg = "#93B878", gui = "bold" }, b = { fg = "#CDC4BA", bg = "#302A24" }, c = { fg = "#8D857D", bg = "#0F0B07" } },
  visual = { a = { fg = "#16110B", bg = "#B98AC4", gui = "bold" }, b = { fg = "#CDC4BA", bg = "#302A24" }, c = { fg = "#8D857D", bg = "#0F0B07" } },
  replace = { a = { fg = "#16110B", bg = "#EA4A3E", gui = "bold" }, b = { fg = "#CDC4BA", bg = "#302A24" }, c = { fg = "#8D857D", bg = "#0F0B07" } },
  command = { a = { fg = "#16110B", bg = "#DDA843", gui = "bold" }, b = { fg = "#CDC4BA", bg = "#302A24" }, c = { fg = "#8D857D", bg = "#0F0B07" } },
  terminal = { a = { fg = "#16110B", bg = "#5FC8D8", gui = "bold" }, b = { fg = "#CDC4BA", bg = "#302A24" }, c = { fg = "#8D857D", bg = "#0F0B07" } },
  inactive = { a = { fg = "#8F8378", bg = "#0F0B07" }, b = { fg = "#8F8378", bg = "#0F0B07" }, c = { fg = "#8F8378", bg = "#0F0B07" } },
}
