-- Ryoku Light for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#EDE6DC", bg = "#B8251B", gui = "bold" }, b = { fg = "#1E1812", bg = "#D0C9C0" }, c = { fg = "#655F58", bg = "#E2D9CC" } },
  insert = { a = { fg = "#EDE6DC", bg = "#2F6024", gui = "bold" }, b = { fg = "#1E1812", bg = "#D0C9C0" }, c = { fg = "#655F58", bg = "#E2D9CC" } },
  visual = { a = { fg = "#EDE6DC", bg = "#4A1A60", gui = "bold" }, b = { fg = "#1E1812", bg = "#D0C9C0" }, c = { fg = "#655F58", bg = "#E2D9CC" } },
  replace = { a = { fg = "#EDE6DC", bg = "#9C1D16", gui = "bold" }, b = { fg = "#1E1812", bg = "#D0C9C0" }, c = { fg = "#655F58", bg = "#E2D9CC" } },
  command = { a = { fg = "#EDE6DC", bg = "#7B5C08", gui = "bold" }, b = { fg = "#1E1812", bg = "#D0C9C0" }, c = { fg = "#655F58", bg = "#E2D9CC" } },
  terminal = { a = { fg = "#EDE6DC", bg = "#07606B", gui = "bold" }, b = { fg = "#1E1812", bg = "#D0C9C0" }, c = { fg = "#655F58", bg = "#E2D9CC" } },
  inactive = { a = { fg = "#6E645A", bg = "#E2D9CC" }, b = { fg = "#6E645A", bg = "#E2D9CC" }, c = { fg = "#6E645A", bg = "#E2D9CC" } },
}
