-- Stone for lualine (LazyVim's status line). Generated by tools/build.py; do not edit.
return {
  normal = { a = { fg = "#D9D0CB", bg = "#7D061F", gui = "bold" }, b = { fg = "#1E1617", bg = "#BFB6B2" }, c = { fg = "#57504F", bg = "#CBC2BE" } },
  insert = { a = { fg = "#D9D0CB", bg = "#0E4001", gui = "bold" }, b = { fg = "#1E1617", bg = "#BFB6B2" }, c = { fg = "#57504F", bg = "#CBC2BE" } },
  visual = { a = { fg = "#D9D0CB", bg = "#5B004B", gui = "bold" }, b = { fg = "#1E1617", bg = "#BFB6B2" }, c = { fg = "#57504F", bg = "#CBC2BE" } },
  replace = { a = { fg = "#D9D0CB", bg = "#7F0011", gui = "bold" }, b = { fg = "#1E1617", bg = "#BFB6B2" }, c = { fg = "#57504F", bg = "#CBC2BE" } },
  command = { a = { fg = "#D9D0CB", bg = "#4A3C00", gui = "bold" }, b = { fg = "#1E1617", bg = "#BFB6B2" }, c = { fg = "#57504F", bg = "#CBC2BE" } },
  terminal = { a = { fg = "#D9D0CB", bg = "#004543", gui = "bold" }, b = { fg = "#1E1617", bg = "#BFB6B2" }, c = { fg = "#57504F", bg = "#CBC2BE" } },
  inactive = { a = { fg = "#5E5052", bg = "#CBC2BE" }, b = { fg = "#5E5052", bg = "#CBC2BE" }, c = { fg = "#5E5052", bg = "#CBC2BE" } },
}
