# Aubergine Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\aubergine-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;51;36;59m"
  Command = "$e[38;2;44;104;41m"
  Keyword = "$e[38;2;150;22;31m"
  String = "$e[38;2;44;104;41m"
  Number = "$e[38;2;75;32;99m"
  Type = "$e[38;2;130;96;3m"
  Operator = "$e[38;2;0;97;101m"
  Variable = "$e[38;2;4;71;130m"
  Member = "$e[38;2;51;36;59m"
  Parameter = "$e[38;2;4;71;130m"
  Comment = "$e[3;38;2;122;106;132m"
  ContinuationPrompt = "$e[38;2;122;106;132m"
  Emphasis = "$e[38;2;159;68;115m"
  Error = "$e[38;2;150;22;31m"
  Selection = "$e[48;2;221;208;227m"
  InlinePrediction = "$e[3;38;2;122;106;132m"
  ListPrediction = "$e[38;2;130;96;3m"
  ListPredictionSelected = "$e[48;2;221;208;227m"
  ListPredictionTooltip = "$e[38;2;122;106;132m"
}
