# Aubergine Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\aubergine-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;239;229;242m"
  Command = "$e[38;2;138;201;117m"
  Keyword = "$e[38;2;245;111;107m"
  String = "$e[38;2;138;201;117m"
  Number = "$e[38;2;188;158;249m"
  Type = "$e[38;2;253;204;102m"
  Operator = "$e[38;2;73;215;206m"
  Variable = "$e[38;2;82;166;238m"
  Member = "$e[38;2;239;229;242m"
  Parameter = "$e[38;2;82;166;238m"
  Comment = "$e[3;38;2;162;144;176m"
  ContinuationPrompt = "$e[38;2;162;144;176m"
  Emphasis = "$e[38;2;246;138;161m"
  Error = "$e[38;2;245;111;107m"
  Selection = "$e[48;2;79;58;94m"
  InlinePrediction = "$e[3;38;2;162;144;176m"
  ListPrediction = "$e[38;2;253;204;102m"
  ListPredictionSelected = "$e[48;2;79;58;94m"
  ListPredictionTooltip = "$e[38;2;162;144;176m"
}
