# Clay for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\clay.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;70;59;60m"
  Command = "$e[38;2;22;90;23m"
  Keyword = "$e[38;2;141;0;29m"
  String = "$e[38;2;22;90;23m"
  Number = "$e[38;2;60;14;85m"
  Type = "$e[38;2;114;78;0m"
  Operator = "$e[38;2;0;85;78m"
  Variable = "$e[38;2;0;58;116m"
  Member = "$e[38;2;70;59;60m"
  Parameter = "$e[38;2;0;58;116m"
  Comment = "$e[3;38;2;102;88;90m"
  ContinuationPrompt = "$e[38;2;102;88;90m"
  Emphasis = "$e[38;2;134;45;65m"
  Error = "$e[38;2;141;0;29m"
  Selection = "$e[48;2;198;184;179m"
  InlinePrediction = "$e[3;38;2;102;88;90m"
  ListPrediction = "$e[38;2;114;78;0m"
  ListPredictionSelected = "$e[48;2;198;184;179m"
  ListPredictionTooltip = "$e[38;2;102;88;90m"
}
