# Forest Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\forest-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;38;54;42m"
  Command = "$e[38;2;45;104;40m"
  Keyword = "$e[38;2;149;25;32m"
  String = "$e[38;2;45;104;40m"
  Number = "$e[38;2;72;33;101m"
  Type = "$e[38;2;132;96;7m"
  Operator = "$e[38;2;0;101;101m"
  Variable = "$e[38;2;6;72;132m"
  Member = "$e[38;2;38;54;42m"
  Parameter = "$e[38;2;6;72;132m"
  Comment = "$e[3;38;2;100;117;104m"
  ContinuationPrompt = "$e[38;2;100;117;104m"
  Emphasis = "$e[38;2;168;71;75m"
  Error = "$e[38;2;149;25;32m"
  Selection = "$e[48;2;210;220;200m"
  InlinePrediction = "$e[3;38;2;100;117;104m"
  ListPrediction = "$e[38;2;132;96;7m"
  ListPredictionSelected = "$e[48;2;210;220;200m"
  ListPredictionTooltip = "$e[38;2;100;117;104m"
}
