# Forest Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\forest-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;230;237;224m"
  Command = "$e[38;2;140;199;117m"
  Keyword = "$e[38;2;252;119;107m"
  String = "$e[38;2;140;199;117m"
  Number = "$e[38;2;202;154;243m"
  Type = "$e[38;2;255;212;108m"
  Operator = "$e[38;2;78;213;200m"
  Variable = "$e[38;2;81;166;240m"
  Member = "$e[38;2;230;237;224m"
  Parameter = "$e[38;2;81;166;240m"
  Comment = "$e[3;38;2;140;160;140m"
  ContinuationPrompt = "$e[38;2;140;160;140m"
  Emphasis = "$e[38;2;229;143;143m"
  Error = "$e[38;2;252;119;107m"
  Selection = "$e[48;2;60;82;66m"
  InlinePrediction = "$e[3;38;2;140;160;140m"
  ListPrediction = "$e[38;2;255;212;108m"
  ListPredictionSelected = "$e[48;2;60;82;66m"
  ListPredictionTooltip = "$e[38;2;140;160;140m"
}
