# Indigo Dusk Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\indigo-dusk-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;232;230;242m"
  Command = "$e[38;2;140;200;116m"
  Keyword = "$e[38;2;246;110;107m"
  String = "$e[38;2;140;200;116m"
  Number = "$e[38;2;204;155;243m"
  Type = "$e[38;2;253;205;103m"
  Operator = "$e[38;2;71;213;208m"
  Variable = "$e[38;2;80;166;238m"
  Member = "$e[38;2;232;230;242m"
  Parameter = "$e[38;2;80;166;238m"
  Comment = "$e[3;38;2;149;148;184m"
  ContinuationPrompt = "$e[38;2;149;148;184m"
  Emphasis = "$e[38;2;254;157;154m"
  Error = "$e[38;2;246;110;107m"
  Selection = "$e[48;2;62;63;99m"
  InlinePrediction = "$e[3;38;2;149;148;184m"
  ListPrediction = "$e[38;2;253;205;103m"
  ListPredictionSelected = "$e[48;2;62;63;99m"
  ListPredictionTooltip = "$e[38;2;149;148;184m"
}
