# Indigo Dusk Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\indigo-dusk-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;42;43;74m"
  Command = "$e[38;2;44;105;41m"
  Keyword = "$e[38;2;148;26;31m"
  String = "$e[38;2;44;105;41m"
  Number = "$e[38;2;59;37;108m"
  Type = "$e[38;2;130;96;0m"
  Operator = "$e[38;2;0;98;102m"
  Variable = "$e[38;2;0;79;143m"
  Member = "$e[38;2;42;43;74m"
  Parameter = "$e[38;2;0;79;143m"
  Comment = "$e[3;38;2;109;108;140m"
  ContinuationPrompt = "$e[38;2;109;108;140m"
  Emphasis = "$e[38;2;165;70;68m"
  Error = "$e[38;2;148;26;31m"
  Selection = "$e[48;2;212;210;232m"
  InlinePrediction = "$e[3;38;2;109;108;140m"
  ListPrediction = "$e[38;2;130;96;0m"
  ListPredictionSelected = "$e[48;2;212;210;232m"
  ListPredictionTooltip = "$e[38;2;109;108;140m"
}
