# Lagoon Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\lagoon-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;227;238;234m"
  Command = "$e[38;2;141;199;115m"
  Keyword = "$e[38;2;251;118;109m"
  String = "$e[38;2;141;199;115m"
  Number = "$e[38;2;197;156;247m"
  Type = "$e[38;2;255;210;107m"
  Operator = "$e[38;2;82;212;195m"
  Variable = "$e[38;2;82;167;238m"
  Member = "$e[38;2;227;238;234m"
  Parameter = "$e[38;2;82;167;238m"
  Comment = "$e[3;38;2;134;163;161m"
  ContinuationPrompt = "$e[38;2;134;163;161m"
  Emphasis = "$e[38;2;235;136;120m"
  Error = "$e[38;2;251;118;109m"
  Selection = "$e[48;2;53;82;90m"
  InlinePrediction = "$e[3;38;2;134;163;161m"
  ListPrediction = "$e[38;2;255;210;107m"
  ListPredictionSelected = "$e[48;2;53;82;90m"
  ListPredictionTooltip = "$e[38;2;134;163;161m"
}
