# Lagoon Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\lagoon-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;31;58;63m"
  Command = "$e[38;2;46;104;37m"
  Keyword = "$e[38;2;147;24;30m"
  String = "$e[38;2;46;104;37m"
  Number = "$e[38;2;76;31;99m"
  Type = "$e[38;2;130;98;12m"
  Operator = "$e[38;2;0;104;93m"
  Variable = "$e[38;2;8;71;131m"
  Member = "$e[38;2;31;58;63m"
  Parameter = "$e[38;2;8;71;131m"
  Comment = "$e[3;38;2;93;118;116m"
  ContinuationPrompt = "$e[38;2;93;118;116m"
  Emphasis = "$e[38;2;163;72;63m"
  Error = "$e[38;2;147;24;30m"
  Selection = "$e[48;2;203;221;217m"
  InlinePrediction = "$e[3;38;2;93;118;116m"
  ListPrediction = "$e[38;2;130;98;12m"
  ListPredictionSelected = "$e[48;2;203;221;217m"
  ListPredictionTooltip = "$e[38;2;93;118;116m"
}
