# Mauve for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\mauve.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;65;54;66m"
  Command = "$e[38;2;21;88;19m"
  Keyword = "$e[38;2;138;0;25m"
  String = "$e[38;2;21;88;19m"
  Number = "$e[38;2;55;10;85m"
  Type = "$e[38;2;104;76;0m"
  Operator = "$e[38;2;0;86;79m"
  Variable = "$e[38;2;0;57;118m"
  Member = "$e[38;2;65;54;66m"
  Parameter = "$e[38;2;0;57;118m"
  Comment = "$e[3;38;2;98;85;96m"
  ContinuationPrompt = "$e[38;2;98;85;96m"
  Emphasis = "$e[38;2;126;43;76m"
  Error = "$e[38;2;138;0;25m"
  Selection = "$e[48;2;192;178;187m"
  InlinePrediction = "$e[3;38;2;98;85;96m"
  ListPrediction = "$e[38;2;104;76;0m"
  ListPredictionSelected = "$e[48;2;192;178;187m"
  ListPredictionTooltip = "$e[38;2;98;85;96m"
}
