# Ryoku Dark for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\ryoku-dark.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;205;196;186m"
  Command = "$e[38;2;147;184;120m"
  Keyword = "$e[38;2;234;74;62m"
  String = "$e[38;2;147;184;120m"
  Number = "$e[38;2;185;138;196m"
  Type = "$e[38;2;221;168;67m"
  Operator = "$e[38;2;95;200;216m"
  Variable = "$e[38;2;99;142;207m"
  Member = "$e[38;2;205;196;186m"
  Parameter = "$e[38;2;99;142;207m"
  Comment = "$e[3;38;2;143;131;120m"
  ContinuationPrompt = "$e[38;2;143;131;120m"
  Emphasis = "$e[38;2;230;61;50m"
  Error = "$e[38;2;234;74;62m"
  Selection = "$e[48;2;42;33;24m"
  InlinePrediction = "$e[3;38;2;143;131;120m"
  ListPrediction = "$e[38;2;221;168;67m"
  ListPredictionSelected = "$e[48;2;42;33;24m"
  ListPredictionTooltip = "$e[38;2;143;131;120m"
}
