# Ryoku Light for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\ryoku-light.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;30;24;18m"
  Command = "$e[38;2;47;96;36m"
  Keyword = "$e[38;2;156;29;22m"
  String = "$e[38;2;47;96;36m"
  Number = "$e[38;2;74;26;96m"
  Type = "$e[38;2;123;92;8m"
  Operator = "$e[38;2;7;96;107m"
  Variable = "$e[38;2;31;69;136m"
  Member = "$e[38;2;30;24;18m"
  Parameter = "$e[38;2;31;69;136m"
  Comment = "$e[3;38;2;110;100;90m"
  ContinuationPrompt = "$e[38;2;110;100;90m"
  Emphasis = "$e[38;2;184;37;27m"
  Error = "$e[38;2;156;29;22m"
  Selection = "$e[48;2;218;207;191m"
  InlinePrediction = "$e[3;38;2;110;100;90m"
  ListPrediction = "$e[38;2;123;92;8m"
  ListPredictionSelected = "$e[48;2;218;207;191m"
  ListPredictionTooltip = "$e[38;2;110;100;90m"
}
