# Stone for PSReadLine (PowerShell typing colors). Generated by tools/build.py; do not edit.
# Dot-source it from $PROFILE:  . '<this repo>\ports\powershell\stone.ps1'
# Needs PSReadLine 2.1+ (Windows PowerShell 5.1 and PowerShell 7 both work).
$e = [char]27
Set-PSReadLineOption -Colors @{
  Default = "$e[38;2;30;22;23m"
  Command = "$e[38;2;14;64;1m"
  Keyword = "$e[38;2;127;0;17m"
  String = "$e[38;2;14;64;1m"
  Number = "$e[38;2;91;0;75m"
  Type = "$e[38;2;74;60;0m"
  Operator = "$e[38;2;0;69;67m"
  Variable = "$e[38;2;0;29;97m"
  Member = "$e[38;2;30;22;23m"
  Parameter = "$e[38;2;0;29;97m"
  Comment = "$e[3;38;2;94;80;82m"
  ContinuationPrompt = "$e[38;2;94;80;82m"
  Emphasis = "$e[38;2;125;6;31m"
  Error = "$e[38;2;127;0;17m"
  Selection = "$e[48;2;189;180;176m"
  InlinePrediction = "$e[3;38;2;94;80;82m"
  ListPrediction = "$e[38;2;74;60;0m"
  ListPredictionSelected = "$e[48;2;189;180;176m"
  ListPredictionTooltip = "$e[38;2;94;80;82m"
}
